language: java
jdk:
- oraclejdk8
os:
- linux
branches:
  only:
  - dev
  - coverity_scan
after_success:
- mvn -DTRAVIS_JOB_ID=$TRAVIS_JOB_ID jacoco:report coveralls:report
env:
  global:
    secure: NEvJTNKsrW7RKBPg0U2gG+A04BNIW2sKE4w5ckEmVOLm9KiEJzcR4ortmNTJYdrHwcdydLhZtzE/MYnHF6mGQNsHTBuEI4NimYDWpidyobbp8fGUWGZ/RFAo7KZMClokAamVf1TbSTPMs/xR6ni+1R/nwmpU4cKMxI3tYlvpfPfuHtT9W8s1zxPPF3cf68She3+4ocH71Il3S2Cqbn9sZrk2AOZvnMYR/cM7IcFn+rE/U1zzLeeRfMiqndqGkbyWcnHRjYNjWBE2vOKxUm9EUyraB86/Bd/s3uHyv/jTvHNDRi3U/tqYNkSpwdOT7MwPD2MJRVpKH6uJmtdN0UEr7Wx+RZzw5EQliZPzXMkluU1VjFIX0dwIOkKtuR8LZoC0pa6guPSiLoSRbSYTFEzgxR93Q8/yQLqhgkEaTV/Zd/plvEyP4xpChAh6d6sANJaLhubnTi/p68VNit86N9bkE8+kZ84OCxkbW75m4Ir9lwjo1W2ErzUlJ39iVz09cZ05imSATVGiQ5HApZ/fUNxojNb9fj2qWCe3zBGrvGWhh0hIWDP4I3OBzNJM/4YSpiHHMzMIKDgzQsOQEpaUm2Zs0xmODw8ZUCutUIJZvoBU8YXraNKhbulnv0p0PeZojj0on/xAATibk6QlzyteVmwp7hoBmdxm4vMp2YFtjqbRBqc=
addons:
  coverity_scan:
    project:
      name: dannil/UrlDatabind
      description: Build submitted via Travis CI
    notification_email: daniel.nilsson94@outlook.com
    build_command_prepend: mvn clean
    build_command: mvn -DskipTests=true compile
    branch_pattern: coverity_scan