language: java
jdk:
- oraclejdk8
os:
- linux
branches:
  only:
  - dev
  - coverity_scan
env:
  global:
    secure: euJCb2eRs1irEs6y5PPBXsOCHiOgXZQJGP7W28XkUwOlvyRtqa8iB8smjcBRvnJfTCHqocun00PiJkgqPtWbe+HGiq5lyz0m3xXhThDqCBx8fLzWDE0OMDg+T8Vkmmeu9GhpA4NZgYcHPi/pGIgEiG7OfNXSDNxwTMVceCsfq4ATOYFnQ7Ak+wlsshx7kTmWHSxbgmLKA3IZ6n1ocYvgrKKJAZLDOPv2Py8Ye2Tf96+Cj/lHN/tSfKlycR5uT0CRB0JwCUx2FQ8opSBGc0+0mwdPf0Qtq0URaSmejUiKnY+Iw3sWcWNKiAxakp9xXPn5rg6hPnpaAMqi3KLjDmlyFDZf9Ip7cxm1h8N9mYPgt4l7s/Tefval/W0DGnZwEAQIf1zFpNKEkfGkWz9wimI6VuA+0Y8o32BowAKJRunQybXxYLIy4C1b03KP5G3LGFvAnwlux1VlGjw9qv7lLuss12QyptfbgjNHiJLuWJDcZbG2nvSNDLoD0SFgzRYGiZMwHlhXcrAshNBjFgdWvyWrndUAj+0uEoW3lX2BRCN8+7rsckQq63uh8HbT71Im2pMafDB7gYOHMcs06Szy2/fvasHnQ5Nioc8ybcuy+zyzsk6kioZbKf/1MaPpyRferbQmJnfk0elLEDik/rqtyGlQlCNnAxqemurAlJ3BVibh52s=
addons:
  coverity_scan:
    project:
      name: dannil/UrlDatabind
      description: Build submitted via Travis CI
    notification_email: bobkant-fyrsvamp@hotmail.com
    build_command_prepend: mvn clean
    build_command: mvn -DskipTests=true compile
    branch_pattern: coverity_scan