language: java
os: linux
dist: xenial

git:
  depth: 99999

branches:
  except:
  - gh-pages

env:
  global:
  - secure: zgiw3J8ZUz32ohb5QMWpc5S2FZyQUpYx4zVk7OuybPU+mGPOKY/dIxZwEnL0u9c7oaRg0JQXIJn0OBnqOv9TZGI8AkFHwuVO1mqeGoTB/7VjmfEpFqcYj8HhSAPF5pkxxGCdmcox490kpjG6SldlJK62eta8dPDBsE83tNu8k388WxdsKvMjuBPgZ9RCa/8WX5QQVkOR4JTqnK1ywy2eIQTSaGYfHFZoE9PYWHyP+yUe+xzBTQ3t9DMTIySmkg3eYS4A2JW2/2PxO6pNVctP4D2eJNBRA4OGpj+D5IXdHQTWfK9SxxRI0GyJZnOFfO5Yp5/qtTBpoHorKB9VedSuLr1B22FHTfQt8TAN1gtbrKJrJdhdbyC6ASD7Xpn/lyHSaI8MeI6h8dSufNVAVx48kYY4GRWfGzy4OPjF540nKkjfAP0o2J9XJx3h/CYWuize0S0BwZO+CmvR7VBPmXzir0QlgzBcdICJCIu49Im295l5Fq47u/6d63F3EQ2I6RP5gDKjzsAW5HOET9fMi4OUApHosJlAYC3Bn5TEwRrf9S/NwnYNJsa/cP8Wnlh/MLCiIIihinPSI7zsNGEyvwrERe1LD6hC62tKA2zuTWmJLbmYD5BMcYhBzD1PQkDA9Oc77zAreI76bZotEIyE9WSIaHn3xMMpJsRGD6YkXbUpNy0=

matrix:
  include:
    - os: linux
      jdk: openjdk8
      # SonarQube addon needs to run with at least Java 8
      after_success:
        # Make sure we are on dev for running SonarQube
        - if [[ $TRAVIS_BRANCH == dev ]]; then 
            mvn sonar:sonar -Dsonar.organization=dannil-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONARQUBE_TOKEN; 
          fi;
    - os: linux
      jdk: openjdk9
    - os: linux
      jdk: openjdk10
    - os: linux
      jdk: openjdk11

install:
- true

script:
- mvn install -Dmaven.javadoc.skip=true -B -V
